name: PR apply

on:
  push:
    paths:
      - 'helm/**'
      - 'terraform/**'
      - 'gihub/workflows/apply.yaml'

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create terraform apply
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1

      - name: terraform plan
        uses: dflook/terraform-apply@v1
        with:
          path: terraform
          auto_approve: true
          var_file: "${GITHUB_REF_NAME}.tfvars"
