name: Docker Build
run-name: Building docker
on:
  push:
    paths:
      - 'Dockerfile'
      - 'app/**'
      - '.github/workflows/build.yaml'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
     DOCKER_TAG: "enriquefrade/mt-app:latest"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_AUTH }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.DOCKER_TAG }}
