name: Docker Build
run-name: Building docker
on:
  pull_request:
    paths:
      - 'Dockerfile'
      - 'app/**'
      - '.github/workflows/build.yaml'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
     DOCKER_IMAGE: "enriquefrade/mt-app:"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Determine Environment
        id: env
        run: |
          BRANCH_NAME=${GITHUB_REF_NAME}
          if [[ "$BRANCH_NAME" == "main" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_AUTH }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGE}} ${{ env.DOCKER_TAG }}
