name: PR Plan

on:
  pull_request:
    paths:
      - 'helm/**'
      - 'terraform/**'
      - '.github/workflows/plan.yaml'

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create terraform plan
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Determine Environment
        id: env
        run: |
          BRANCH_NAME=${GITHUB_REF_NAME}
          if [[ "$BRANCH_NAME" == "main" ]]; then
            echo "ENV=prd" >> $GITHUB_ENV
          else
            echo "ENV=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          fi

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: terraform
          var_file: terraform/env/${{ env.ENV }}.tfvars
          backend_config_file: terraform/env/backend/${{ env.ENV }}.tfvars

      - name: Comment PR with Terraform Plan Output
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ## Terraform Plan Output 🏗️
            ```
            ${{ steps.tf_plan.outputs.stdout }}
            ```
          repo-token: ${{ secrets.GITHUB_TOKEN }}
